######################################################################
##
## Filename: tb_clk_prescaler.udo
## Created on: Wed Nov 19 07:47:15 PM CST 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
